name: Publish

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: false

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno test -A

  publish:
    runs-on: ubuntu-latest
    needs: test
    continue-on-error: false

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Publish package
        run: deno publish
